// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from '@hey-api/client-fetch';
import type {
  TakeSecretSecretsSecretKeyGetData,
  TakeSecretSecretsSecretKeyGetError,
  TakeSecretSecretsSecretKeyGetResponse,
  CreateSecretGeneratePostData,
  CreateSecretGeneratePostError,
  CreateSecretGeneratePostResponse,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * Take Secret
 */
export const takeSecretSecretsSecretKeyGet = <
  ThrowOnError extends boolean = false
>(
  options: Options<TakeSecretSecretsSecretKeyGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    TakeSecretSecretsSecretKeyGetResponse,
    TakeSecretSecretsSecretKeyGetError,
    ThrowOnError
  >({
    ...options,
    url: '/secrets/{secret_key}',
  });
};

/**
 * Create Secret
 */
export const createSecretGeneratePost = <ThrowOnError extends boolean = false>(
  options: Options<CreateSecretGeneratePostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateSecretGeneratePostResponse,
    CreateSecretGeneratePostError,
    ThrowOnError
  >({
    ...options,
    url: '/generate',
  });
};
